name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git unzip xz-utils zip libglu1-mesa

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

    - name: Debug Flutter PATH
      run: |
        export PATH="$PATH:`pwd`/flutter/bin"
        echo "Current PATH: $PATH"
        ls `pwd`/flutter/bin
        flutter --version

    - name: Install Flutter dependencies
      run: |
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter pub get

    - name: Build Flutter Web App
      run: |
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter build web

    - name: Add .nojekyll to root
      run: echo "" > build/web/.nojekyll

    - name: Copy index.html to 404.html
      run: cp build/web/index.html build/web/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
