name: Build and Deploy Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        $env:PATH = "$env:PATH;$pwd/flutter/bin"
        flutter doctor

    - name: Install dependencies
      run: |
        $env:PATH = "$env:PATH;$pwd/flutter/bin"
        flutter pub get

    - name: Build Windows release
      run: |
        $env:PATH = "$env:PATH;$pwd/flutter/bin"
        flutter build windows

    - name: Archive the build artifacts
      run: |
        mkdir build_artifacts
        Copy-Item -Path build/windows/x64/runner/Release/* -Destination build_artifacts/ -Recurse
        Compress-Archive -Path build_artifacts/* -DestinationPath build/windows_build.zip

    - name: Create or Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows_build.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: latest
        name: "Latest Windows Build"
        prerelease: true
